export enum MarketSignal {
  BRENT_CRUDE = 'BRENT_CRUDE',
  WTI_CRUDE = 'WTI_CRUDE',
  HENRY_HUB_GAS = 'HENRY_HUB_GAS',
  TTF_GAS = 'TTF_GAS',
  LPG_INDEX = 'LPG_INDEX',
  NAPHTHA = 'NAPHTHA',
  FREIGHT_CONTAINER_INDEX = 'FREIGHT_CONTAINER_INDEX',
  DRY_BULK_INDEX = 'DRY_BULK_INDEX',
}
